// Code generated by protomq:go; DO NOT EDIT.

package test_package

import (
	"github.com/segmentio/kafka-go"
	"github.com/yoozoo/protomq/goconsumer"
)

type jsonqueueHandler func(string) error

var jsonqueueConsumer = goconsumer.NewConsumer()

// RegisterJsonQueueHandler register kafka message handler
func RegisterJsonQueueHandler(handler jsonqueueHandler) {
	h := func(m *kafka.Message) error {
		return handler(string(m.Value))
	}
	jsonqueueConsumer.RegisterHandler(h)
}

//  RunJsonQueueConsumer runs go consumer
// Need to register handler first
func RunJsonQueueConsumer() {
	jsonqueueConsumer.SetTopic("test")
	jsonqueueConsumer.Run()
}
