// Code generated by protomq:go; DO NOT EDIT.

package test_package

import (
	"github.com/golang/protobuf/proto"
	"github.com/segmentio/kafka-go"
	"github.com/yoozoo/protomq/goconsumer"
)

type typedqueueHandler func(*TypedQueue) error

var typedqueueConsumer = goconsumer.NewConsumer()

// RegisterTypedQueueHandler register kafka message handler
func RegisterTypedQueueHandler(handler typedqueueHandler) {
	h := func(m *kafka.Message) error {
		message := &TypedQueue{}
		if err := proto.Unmarshal(m.Value, message); err != nil {
			return err
		}
		return handler(message)
	}
	typedqueueConsumer.RegisterHandler(h)
}

//  RunTypedQueueConsumer runs go consumer
// Need to register handler first
func RunTypedQueueConsumer() {
	typedqueueConsumer.SetTopic("test_typed")
	typedqueueConsumer.Run()
}
