// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JsonQueue struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JsonQueue) Reset()         { *m = JsonQueue{} }
func (m *JsonQueue) String() string { return proto.CompactTextString(m) }
func (*JsonQueue) ProtoMessage()    {}
func (*JsonQueue) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *JsonQueue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JsonQueue.Unmarshal(m, b)
}
func (m *JsonQueue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JsonQueue.Marshal(b, m, deterministic)
}
func (m *JsonQueue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JsonQueue.Merge(m, src)
}
func (m *JsonQueue) XXX_Size() int {
	return xxx_messageInfo_JsonQueue.Size(m)
}
func (m *JsonQueue) XXX_DiscardUnknown() {
	xxx_messageInfo_JsonQueue.DiscardUnknown(m)
}

var xxx_messageInfo_JsonQueue proto.InternalMessageInfo

func (m *JsonQueue) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Log struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Log) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type TypedQueue struct {
	Data                 *Log     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypedQueue) Reset()         { *m = TypedQueue{} }
func (m *TypedQueue) String() string { return proto.CompactTextString(m) }
func (*TypedQueue) ProtoMessage()    {}
func (*TypedQueue) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *TypedQueue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypedQueue.Unmarshal(m, b)
}
func (m *TypedQueue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypedQueue.Marshal(b, m, deterministic)
}
func (m *TypedQueue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypedQueue.Merge(m, src)
}
func (m *TypedQueue) XXX_Size() int {
	return xxx_messageInfo_TypedQueue.Size(m)
}
func (m *TypedQueue) XXX_DiscardUnknown() {
	xxx_messageInfo_TypedQueue.DiscardUnknown(m)
}

var xxx_messageInfo_TypedQueue proto.InternalMessageInfo

func (m *TypedQueue) GetData() *Log {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*JsonQueue)(nil), "JsonQueue")
	proto.RegisterType((*Log)(nil), "Log")
	proto.RegisterType((*TypedQueue)(nil), "TypedQueue")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0xe2, 0x05, 0x53, 0xb9, 0x85, 0x10, 0xae, 0x92, 0x26,
	0x17, 0xa7, 0x57, 0x71, 0x7e, 0x5e, 0x60, 0x69, 0x6a, 0x69, 0xaa, 0x90, 0x10, 0x17, 0x4b, 0x4a,
	0x62, 0x49, 0xa2, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x6d, 0xc5, 0xd1, 0xf4, 0x4e,
	0x8a, 0x05, 0xa4, 0x5f, 0xc9, 0x90, 0x8b, 0xd9, 0x27, 0x3f, 0x5d, 0x48, 0x80, 0x8b, 0x39, 0xb7,
	0x38, 0x1d, 0xaa, 0x06, 0xc4, 0x14, 0x92, 0xe0, 0x62, 0x2f, 0x4b, 0x2d, 0x2a, 0xce, 0xcc, 0xcf,
	0x93, 0x60, 0x52, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x71, 0x95, 0xcc, 0xb8, 0xb8, 0x42, 0x2a, 0x0b,
	0x52, 0x53, 0x20, 0xc6, 0x4b, 0x20, 0x19, 0xcf, 0x6d, 0xc4, 0xa2, 0xe7, 0x93, 0x9f, 0x0e, 0xb5,
	0x84, 0xaf, 0xe9, 0x9d, 0x14, 0xd8, 0x91, 0xf1, 0x25, 0x20, 0xe5, 0x49, 0x6c, 0x60, 0xc7, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x06, 0x08, 0x50, 0xb9, 0x00, 0x00, 0x00,
}
