<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TypedQueue</code>
 */
class TypedQueue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Log data = 1;</code>
     */
    private $data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Log $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Test::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Log data = 1;</code>
     * @return \Log
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>.Log data = 1;</code>
     * @param \Log $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Log::class);
        $this->data = $var;

        return $this;
    }

}

