<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

namespace GPBMetadata;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Protomq::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aab010a0a746573742e70726f746f120c746573745f7061636b61676522" .
            "230a094a736f6e5175657565120c0a04646174611801200128093a0882ee" .
            "1a047465737422230a034c6f67120b0a036d7367180120012809120f0a07" .
            "76657273696f6e180220012805223d0a0a54797065645175657565121f0a" .
            "046461746118012001280b32112e746573745f7061636b6167652e4c6f67" .
            "3a0e82ee1a0a746573745f7479706564620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

