<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

namespace GPBMetadata;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Protomq::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a90010a0a746573742e70726f746f22230a094a736f6e5175657565120c" .
            "0a04646174611801200128093a0882ee1a047465737422230a034c6f6712" .
            "0b0a036d7367180120012809120f0a0776657273696f6e18022001280522" .
            "300a0a5479706564517565756512120a046461746118012001280b32042e" .
            "4c6f673a0e82ee1a0a746573745f7479706564620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

