<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protomq.proto

namespace GPBMetadata;

class Protomq
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a4e0a0d70726f746f6d712e70726f746f120770726f746f6d711a20676f" .
            "6f676c652f70726f746f6275662f64657363726970746f722e70726f746f" .
            "420a5a086d71636f6d6d6f6e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}
