// Code generated by "esc -o tpl/tpl.go -modtime 0 -pkg=tpl template protomq.proto"; DO NOT EDIT.

package tpl

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return []os.FileInfo(fis[0:limit]), nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/protomq.proto": {
		name:    "protomq.proto",
		local:   "protomq.proto",
		size:    181,
		modtime: 0,
		compressed: `
H4sIAAAAAAAC/zSMUarCMBBF/2cVlyygLTwKD0qXIC5BYjqGoMmkyQgVce/SSH/vuefUV1K7YYbJRVT+
zEQUYpaiMF7EP7hv4Pq89QtXV0JWKV3b9m+27m49ow1xnYgka5AEL5eDzTBxdRKjpF3hTTkt+NW7o96d
uFbr+dz0ijcBVUtIHio5OMwYx2H4n+hD3wAAAP//vsI68bUAAAA=
`,
	},

	"/template/go/client.gogo": {
		name:    "client.gogo",
		local:   "template/go/client.gogo",
		size:    914,
		modtime: 0,
		compressed: `
H4sIAAAAAAAC/6xSPW/bMBCdeb/iqiGQAkfeVXix06FA7TSI0Q5BBlo6MYQlUiUpuIbA/16QVPMBZ4ym
E967e+8eb7nEjW4IBSky3FGDhzMORjvd/6mE/oq3d7i72+O32+/7EmDg9ZELwmkqf6bSewDZD9o4zIFl
tVaO/roMABFxmm5Qtlg+OKOV2J+HQGeZkO55PJS17pdCd1yJZVQ8jG0qspdmUk3oOPL2yPFtnyXRk3JS
LyN2I3QGBYA7D9Hcjvfk/fZ+00lSDq0zY+1winNPeB17yt9GOjLgAdpR1bij02VnfjD6SMbi45N1RipR
4PUlKw025Eaj8OoCT3DUrjBp7+iU5PO3XjZatVK80sO3TgYqxNnK4h2814Osq1Bl01TGP++z95w177iq
yVR4ldR+ELdufXZkJ/9K9UWq/Uskef3BtsUDqSbvrQhB3480UnrYAnMyBskYbYo5ko8PoOGOLwIRq1U6
tnLLjX3mXRhbAJNtRL+sUMkOJ2AsZQvMA7AArbAuTym1LVnLBdl8vr1yzeujMHpUTV4sgKXrKWdaGMZ+
8W6kCqMPYMwvgBWzX6TOEgaXnybz+HQ4O4qrXaqpJojB/wU9/AsAAP//EFC9DZIDAAA=
`,
	},

	"/template/php/consumer.gophp": {
		name:    "consumer.gophp",
		local:   "template/php/consumer.gophp",
		size:    1057,
		modtime: 0,
		compressed: `
H4sIAAAAAAAC/4xTXWvbMBR916+4FINlaLwf4LWDrqzsYV0WZ+wlEBTp1ha1Je9KbhaE//uwYvLVDKYn
cX3u8TnnXn381NUdM6JF1wmJEALkcyFfRYXPokUYhoKx3iGUnSbRrJ4saVVhcVpbWKEWvTFIBWPa6LVD
z1OlXdeI3RqJLLn0FlLnFRKlWcEIf/eaENI3NMrSB9F721ih8q7u0oKxEGagXyAvPVlTLXcdDgPTRja9
Qkif5g/f0AslvFiFkD89zIdh6jxgQshH/YcPIyMaNQyMiY3zJKQH2QjnouPP423yywIDAOjIepQeFSQ0
+oq1ftNoCS+9kV5bA+u1tMZ56qXnWUTse8eT+Fq72T0R3IHBLRxDWv2y9IrEx+p5qqvSE4p2gY3Y8XL5
+PX5Fsrl4/efyywrIvNwXQj15p2Aba0bBJ5srNrB3VHP7J5Qon5DnkhrPP7xWXbSNh5Pu4tKpL42lEtQ
0rpqchxC/qPHHvdIPjm4BM/uW6QKv5BtS0/aVHvF19B7B7UwqsF16yo+9l8Bxlk3Lg7zP0j+8buTjXlH
Mqbo0Ch+c3ML3EXdGRzyPCcbQAova+CrZU12KzYNQoLZlYQjb3wv/EiKl3Ts/DbpO2z1cXEP63HiNoTL
EZ6PKYToGaZoB/Y3AAD//915QKghBAAA
`,
	},

	"/template/php/producer.gophp": {
		name:    "producer.gophp",
		local:   "template/php/producer.gophp",
		size:    590,
		modtime: 0,
		compressed: `
H4sIAAAAAAAC/2yQQW+cMBCF7/4VI8QBVllCemkkCq2UQ29VGvYYKZraE2LFsS3bpKKW/3uFQWmi7VyG
GR5vPt6Xr/bJMo0v5C1yghihuUX+jBP9wBeClDrGZk8wWulQ3X83ToqJOsa4Qu+z/mZ92tUsMgCAy8Mh
dzjAt1d0sH92f3d7s+8vc7dOvmIgKJ3lHdtW8y8lOTzOmgdpNDw8cKN9cDMPVYlCOOihuPr0uWmbtrkq
LqC0xgXo4bq9butssTGsVYYn6Y+Dsxx60PT7PUj1fh4Nf6ZwRwqX7cruW9ddNkv/h/OkRRWjfIRmDM7o
6bRYSinG5udMM20TxEhapFQKDHhGaHFRBgX0gM7hUr29WasIxkpeQD9AsUZ9WkdIqbj4KONGB9IhC/OZ
c6bj4MlJVPIPncwYnNRTVe9k/9z23/2Y3XHgqFRVjKQFuWZtOfeN/C2hxP4GAAD//8nzRZ1OAgAA
`,
	},

	"/template": {
		name:  "template",
		local: `template`,
		isDir: true,
	},

	"/template/go": {
		name:  "go",
		local: `template/go`,
		isDir: true,
	},

	"/template/php": {
		name:  "php",
		local: `template/php`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"template": {
		_escData["/template/go"],
		_escData["/template/php"],
	},

	"template/go": {
		_escData["/template/go/client.gogo"],
	},

	"template/php": {
		_escData["/template/php/consumer.gophp"],
		_escData["/template/php/producer.gophp"],
	},
}
