// Code generated by protomq:go; DO NOT EDIT.

package test_package

import (
	"context"
	kafka "github.com/segmentio/kafka-go"
)

type JsonQueueMQClient struct {
	w *kafka.Writer
}

func NewJsonQueueMQClient(brokers []string) *JsonQueueMQClient {
	return &JsonQueueMQClient{
		w: kafka.NewWriter(kafka.WriterConfig{
			Brokers:  brokers,
			Topic:    "test",
			Balancer: &kafka.LeastBytes{},
		}),
	}
}

func (c *JsonQueueMQClient) Send(msg string) (err error) {
	err = c.w.WriteMessages(context.Background(),
		kafka.Message{
			Value: []byte(msg),
		},
	)

	return
}
