// Code generated by protomq:go; DO NOT EDIT.

package test_package

import (
	"context"
	"github.com/golang/protobuf/proto"
	kafka "github.com/segmentio/kafka-go"
)

type TypedQueueMQClient struct {
	w *kafka.Writer
}

func NewTypedQueueMQClient(brokers []string) *TypedQueueMQClient {
	return &TypedQueueMQClient{
		w: kafka.NewWriter(kafka.WriterConfig{
			Brokers:  brokers,
			Topic:    "test_typed",
			Balancer: &kafka.LeastBytes{},
		}),
	}
}

func (c *TypedQueueMQClient) Send(msg *TypedQueue) (err error) {
	data, err := proto.Marshal(msg)
	if err != nil {
		return
	}

	err = c.w.WriteMessages(context.Background(),
		kafka.Message{
			Value: data,
		},
	)

	return
}
